package com.bica.reborn.testgen;

import com.bica.reborn.exception.ProtocolViolationException;
import com.bica.reborn.statespace.StateSpace;
import com.bica.reborn.statespace.TransitionKind;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates JUnit 5 test source from a session type state space.
 *
 * <p>Produces three categories of tests:
 * <ol>
 *   <li><b>Valid paths</b> &mdash; complete top-to-bottom protocol traces</li>
 *   <li><b>Violations</b> &mdash; calls to disabled methods at each state</li>
 *   <li><b>Incomplete protocols</b> &mdash; prefixes that leave the object in a non-terminal state</li>
 * </ol>
 *
 * <p>Violation tests assert {@link ProtocolViolationException} rather than the
 * generic {@link IllegalStateException}, preventing false passes from unrelated
 * state errors.
 */
public final class TestGenerator {

    private TestGenerator() {}

    /**
     * Generates a complete JUnit 5 test class source string.
     *
     * @param ss          the state space to generate tests from
     * @param config      test generation configuration
     * @param sessionType pretty-printed session type string (for the header comment)
     * @return JUnit 5 Java source code
     */
    public static String generate(StateSpace ss, TestGenConfig config, String sessionType) {
        var result = PathEnumerator.enumerate(ss, config);
        var cpResult = PathEnumerator.enumerateClientPrograms(ss,
                config.maxRevisits(), config.maxPaths());
        var sb = new StringBuilder();

        // Package declaration
        if (config.packageName() != null && !config.packageName().isBlank()) {
            sb.append("package ").append(config.packageName()).append(";\n\n");
        }

        // Imports
        sb.append("import com.bica.reborn.exception.ProtocolViolationException;\n");
        sb.append("import org.junit.jupiter.api.Test;\n");
        sb.append("import org.junit.jupiter.api.Disabled;\n");
        if (config.violationStyle() == ViolationStyle.CALL_ANYWAY) {
            sb.append("import static org.junit.jupiter.api.Assertions.*;\n");
        }
        sb.append("\n");

        // Class javadoc
        sb.append("/**\n");
        sb.append(" * Protocol conformance tests for ").append(config.className()).append(".\n");
        sb.append(" * Session type: ").append(sessionType).append("\n");
        sb.append(" * Generated by BICA Reborn test generator.\n");
        sb.append(" */\n");

        // Class declaration
        sb.append("class ").append(config.className()).append("ProtocolTest {\n");

        // Valid paths (client programs with switch statements)
        appendClientPrograms(sb, cpResult.programs(), config, cpResult.truncated());

        // Violations
        appendViolations(sb, result.violations(), config);

        // Incomplete protocols
        appendIncompletePrefixes(sb, result.incompletePrefixes(), config);

        sb.append("}\n");
        return sb.toString();
    }

    // =========================================================================
    // Valid paths (client programs with switch statements)
    // =========================================================================

    private static void appendClientPrograms(StringBuilder sb,
                                              List<PathEnumerator.ClientProgram> programs,
                                              TestGenConfig config, boolean truncated) {
        sb.append("\n    // ===== Valid paths (").append(programs.size()).append(") =====\n");

        if (truncated) {
            sb.append("\n    // WARNING: path enumeration truncated at ")
              .append(config.maxPaths())
              .append(" paths\n");
        }

        for (var program : programs) {
            String suffix = clientProgramNameSuffix(program);
            String methodSuffix = suffix.isEmpty() ? "empty" : suffix;
            sb.append("\n    @Test\n");
            sb.append("    void validPath_").append(methodSuffix).append("() {\n");
            sb.append("        ").append(config.className()).append(" ")
              .append(config.varName()).append(" = new ")
              .append(config.className()).append("();\n");
            var varCounts = new HashMap<String, Integer>();
            appendClientProgram(sb, program, config.varName(), "        ", varCounts);
            sb.append("    }\n");
        }
    }

    /**
     * Recursively emits Java code for a client program tree.
     */
    private static void appendClientProgram(StringBuilder sb,
                                             PathEnumerator.ClientProgram cp,
                                             String varName,
                                             String indent,
                                             Map<String, Integer> varCounts) {
        switch (cp) {
            case PathEnumerator.ClientProgram.Terminal t -> {
                // nothing — protocol complete
            }
            case PathEnumerator.ClientProgram.MethodCall mc -> {
                sb.append(indent).append(varName).append(".").append(mc.label()).append("();\n");
                appendClientProgram(sb, mc.next(), varName, indent, varCounts);
            }
            case PathEnumerator.ClientProgram.SelectionSwitch sw -> {
                // var {method}Result = obj.{method}();
                String resultVar = resultVarName(sw.methodLabel(), varCounts);
                sb.append(indent).append("var ").append(resultVar)
                  .append(" = ").append(varName).append(".")
                  .append(sw.methodLabel()).append("();\n");
                sb.append(indent).append("switch (").append(resultVar).append(") {\n");
                for (var entry : sw.branches().entrySet()) {
                    sb.append(indent).append("    case ").append(entry.getKey()).append(" -> {\n");
                    appendClientProgram(sb, entry.getValue(), varName,
                            indent + "        ", varCounts);
                    sb.append(indent).append("    }\n");
                }
                sb.append(indent).append("}\n");
            }
        }
    }

    /**
     * Generates a unique result variable name for a method call.
     * First call: {@code mResult}, subsequent: {@code mResult2}, {@code mResult3}, etc.
     */
    private static String resultVarName(String methodLabel, Map<String, Integer> varCounts) {
        int count = varCounts.merge(methodLabel, 1, Integer::sum);
        return count == 1
                ? methodLabel + "Result"
                : methodLabel + "Result" + count;
    }

    /**
     * Collects METHOD labels depth-first from a client program tree for test naming.
     * Selection labels are excluded; all switch branches are traversed.
     */
    static String clientProgramNameSuffix(PathEnumerator.ClientProgram cp) {
        var labels = new ArrayList<String>();
        collectMethodLabels(cp, labels);
        return String.join("_", labels);
    }

    private static void collectMethodLabels(PathEnumerator.ClientProgram cp, List<String> labels) {
        switch (cp) {
            case PathEnumerator.ClientProgram.Terminal t -> {}
            case PathEnumerator.ClientProgram.MethodCall mc -> {
                labels.add(mc.label());
                collectMethodLabels(mc.next(), labels);
            }
            case PathEnumerator.ClientProgram.SelectionSwitch sw -> {
                labels.add(sw.methodLabel());
                for (var branch : sw.branches().values()) {
                    collectMethodLabels(branch, labels);
                }
            }
        }
    }

    // =========================================================================
    // Violations
    // =========================================================================

    private static void appendViolations(StringBuilder sb, List<PathEnumerator.ViolationPoint> violations,
                                          TestGenConfig config) {
        sb.append("\n    // ===== Violations (").append(violations.size()).append(") =====\n");

        for (var v : violations) {
            List<String> prefixLabels = v.prefixLabels();
            Set<String> enabledSorted = new TreeSet<>(v.enabledMethods());
            String stateDesc = prefixLabels.isEmpty() ? "initial state" : "state after [" + String.join(", ", prefixLabels) + "]";
            String enabledStr = "[" + String.join(", ", enabledSorted) + "]";

            String methodSuffix = prefixLabels.isEmpty()
                    ? "initial_" + v.disabledMethod()
                    : String.join("_", prefixLabels) + "_" + v.disabledMethod();

            if (config.violationStyle() == ViolationStyle.DISABLED_ANNOTATION) {
                String disabledReason = "Protocol violation: '" + v.disabledMethod()
                          + "' not enabled in " + stateDesc
                          + "; enabled: " + enabledStr;
                sb.append("\n    @Disabled(\"").append(disabledReason).append("\")\n");
                sb.append("    @Test\n");
                sb.append("    void violation_").append(methodSuffix).append("() {\n");
                sb.append("        ").append(config.className()).append(" ")
                  .append(config.varName()).append(" = new ")
                  .append(config.className()).append("();\n");
                for (var step : v.prefixPath()) {
                    appendStep(sb, step, config.varName());
                }
                sb.append("        ").append(config.varName()).append(".")
                  .append(v.disabledMethod()).append("(); // VIOLATION: not enabled here\n");
                sb.append("    }\n");
            } else {
                // CALL_ANYWAY — all violations use assertThrows
                sb.append("\n    @Test\n");
                sb.append("    void violation_").append(methodSuffix).append("() {\n");
                sb.append("        ").append(config.className()).append(" ")
                  .append(config.varName()).append(" = new ")
                  .append(config.className()).append("();\n");
                for (var step : v.prefixPath()) {
                    appendStep(sb, step, config.varName());
                }
                sb.append("        assertThrows(ProtocolViolationException.class, () -> ")
                  .append(config.varName()).append(".").append(v.disabledMethod())
                  .append("());\n");
                sb.append("    }\n");
            }
        }
    }

    // =========================================================================
    // Incomplete protocols
    // =========================================================================

    private static void appendStep(StringBuilder sb, PathEnumerator.Step step, String varName) {
        if (step.kind() == TransitionKind.SELECTION) {
            sb.append("        // -> ").append(step.label()).append(" (selected by object)\n");
        } else {
            sb.append("        ").append(varName).append(".").append(step.label()).append("();\n");
        }
    }

    private static void appendIncompletePrefixes(StringBuilder sb,
                                                  List<PathEnumerator.IncompletePrefix> prefixes,
                                                  TestGenConfig config) {
        sb.append("\n    // ===== Incomplete protocols (").append(prefixes.size()).append(") =====\n");

        for (var p : prefixes) {
            List<String> labels = p.labels();
            Set<String> remainingSorted = new TreeSet<>(p.remainingMethods());
            String labelsStr = "[" + String.join(", ", labels) + "]";
            String remainingStr = "[" + String.join(", ", remainingSorted) + "]";
            String methodSuffix = String.join("_", labels);

            sb.append("\n    @Disabled(\"Incomplete: object not in terminal state after ")
              .append(labelsStr).append("\")\n");
            sb.append("    @Test\n");
            sb.append("    void incomplete_").append(methodSuffix).append("() {\n");
            sb.append("        ").append(config.className()).append(" ")
              .append(config.varName()).append(" = new ")
              .append(config.className()).append("();\n");
            for (var step : p.steps()) {
                appendStep(sb, step, config.varName());
            }
            sb.append("        // NOT COMPLETE: enabled methods remain: ").append(remainingStr).append("\n");
            sb.append("    }\n");
        }
    }
}
