package com.bica.reborn.testgen;

import com.bica.reborn.parser.Parser;
import com.bica.reborn.parser.PrettyPrinter;
import com.bica.reborn.statespace.StateSpace;
import com.bica.reborn.statespace.StateSpaceBuilder;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class TestGeneratorTest {

    private static StateSpace ss(String source) {
        return StateSpaceBuilder.build(Parser.parse(source));
    }

    private static String generate(String source, TestGenConfig config) {
        var ast = Parser.parse(source);
        return TestGenerator.generate(StateSpaceBuilder.build(ast), config, PrettyPrinter.pretty(ast));
    }

    private static String generate(String source) {
        return generate(source, TestGenConfig.withDefaults("Obj"));
    }

    // =========================================================================
    // Structure
    // =========================================================================

    @Nested
    class Structure {

        @Test
        void containsClassDeclaration() {
            var out = generate("end");
            assertTrue(out.contains("class ObjProtocolTest {"));
        }

        @Test
        void containsImports() {
            var out = generate("end");
            assertTrue(out.contains("import org.junit.jupiter.api.Test;"));
            assertTrue(out.contains("import org.junit.jupiter.api.Disabled;"));
        }

        @Test
        void containsJavadoc() {
            var out = generate("end");
            assertTrue(out.contains("Protocol conformance tests for Obj."));
            assertTrue(out.contains("Generated by BICA Reborn test generator."));
        }

        @Test
        void containsSessionTypeInJavadoc() {
            var out = generate("a . b . end");
            assertTrue(out.contains("Session type: a . b . end"));
        }

        @Test
        void containsValidPathsSection() {
            var out = generate("end");
            assertTrue(out.contains("Valid paths"));
        }

        @Test
        void containsViolationsSection() {
            var out = generate("end");
            assertTrue(out.contains("Violations"));
        }

        @Test
        void containsIncompleteSection() {
            var out = generate("end");
            assertTrue(out.contains("Incomplete protocols"));
        }

        @Test
        void closingBrace() {
            var out = generate("end");
            assertTrue(out.trim().endsWith("}"));
        }
    }

    // =========================================================================
    // Package declaration
    // =========================================================================

    @Nested
    class PackageDeclaration {

        @Test
        void noPackageByDefault() {
            var out = generate("end");
            assertFalse(out.startsWith("package"));
        }

        @Test
        void withPackage() {
            var out = generate("end", TestGenConfig.withPackage("Obj", "com.example"));
            assertTrue(out.startsWith("package com.example;"));
        }

        @Test
        void blankPackageOmitted() {
            var out = generate("end", new TestGenConfig("Obj", "  ", "obj", 2, 100, ViolationStyle.DISABLED_ANNOTATION));
            assertFalse(out.startsWith("package"));
        }
    }

    // =========================================================================
    // Valid path tests
    // =========================================================================

    @Nested
    class ValidPathTests {

        @Test
        void endType_emptyPath() {
            var out = generate("end");
            assertTrue(out.contains("validPath_empty"));
            assertTrue(out.contains("new Obj()"));
        }

        @Test
        void simpleChain() {
            var out = generate("a . b . end");
            assertTrue(out.contains("validPath_a_b"));
            assertTrue(out.contains("obj.a()"));
            assertTrue(out.contains("obj.b()"));
        }

        @Test
        void branchTwoPaths() {
            var out = generate("&{m: end, n: end}");
            assertTrue(out.contains("validPath_m"));
            assertTrue(out.contains("validPath_n"));
        }

        @Test
        void usesCustomClassName() {
            var config = TestGenConfig.withDefaults("FileHandle");
            var out = generate("a . end", config);
            assertTrue(out.contains("FileHandle obj = new FileHandle()"));
            assertTrue(out.contains("class FileHandleProtocolTest"));
        }

        @Test
        void usesCustomVarName() {
            var config = new TestGenConfig("Obj", null, "sut", 2, 100, ViolationStyle.DISABLED_ANNOTATION);
            var out = generate("a . end", config);
            assertTrue(out.contains("Obj sut = new Obj()"));
            assertTrue(out.contains("sut.a()"));
        }

        @Test
        void validPathHasTestAnnotation() {
            var out = generate("a . end");
            assertTrue(out.contains("@Test"));
            assertTrue(out.contains("void validPath_a()"));
        }

        @Test
        void truncationWarning() {
            var config = new TestGenConfig("Obj", null, "obj", 2, 1, ViolationStyle.DISABLED_ANNOTATION);
            var out = generate("&{a: end, b: end}", config);
            assertTrue(out.contains("WARNING: path enumeration truncated"));
        }

        @Test
        void noTruncationWarningWhenUnderLimit() {
            var out = generate("a . end");
            assertFalse(out.contains("WARNING"));
        }
    }

    // =========================================================================
    // Violation tests
    // =========================================================================

    @Nested
    class ViolationTests {

        @Test
        void disabledAnnotationStyle() {
            var out = generate("a . b . end");
            assertTrue(out.contains("@Disabled("));
            assertTrue(out.contains("Protocol violation:"));
        }

        @Test
        void violationCallsDisabledMethod() {
            var out = generate("a . b . end");
            assertTrue(out.contains("VIOLATION: not enabled here"));
        }

        @Test
        void callAnywayStyle() {
            var config = new TestGenConfig("Obj", null, "obj", 2, 100, ViolationStyle.CALL_ANYWAY);
            var out = generate("a . b . end", config);
            assertTrue(out.contains("assertThrows(ProtocolViolationException.class"));
            // Violation tests don't use @Disabled, but incomplete prefixes still do
            assertTrue(out.contains("@Disabled(\"Incomplete:"));
        }

        @Test
        void callAnywayImportsAssertions() {
            var config = new TestGenConfig("Obj", null, "obj", 2, 100, ViolationStyle.CALL_ANYWAY);
            var out = generate("a . b . end", config);
            assertTrue(out.contains("import static org.junit.jupiter.api.Assertions.*;"));
        }

        @Test
        void violationShowsEnabledMethods() {
            // a . b . end has violations where 'enabled:' is shown
            var out = generate("a . b . end");
            assertTrue(out.contains("enabled:"));
        }

        @Test
        void noViolationsForSingleMethod() {
            var out = generate("a . end");
            assertTrue(out.contains("Violations (0)"));
        }
    }

    // =========================================================================
    // Incomplete protocol tests
    // =========================================================================

    @Nested
    class IncompletePrefixTests {

        @Test
        void endType_noIncomplete() {
            var out = generate("end");
            assertTrue(out.contains("Incomplete protocols (0)"));
        }

        @Test
        void chainHasIncomplete() {
            var out = generate("a . b . end");
            assertTrue(out.contains("incomplete_a"));
            assertTrue(out.contains("NOT COMPLETE: enabled methods remain:"));
        }

        @Test
        void incompleteHasDisabledAnnotation() {
            var out = generate("a . b . end");
            assertTrue(out.contains("@Disabled(\"Incomplete:"));
        }

        @Test
        void incompleteShowsPrefix() {
            var out = generate("a . b . end");
            assertTrue(out.contains("object not in terminal state after [a]"));
        }
    }

    // =========================================================================
    // End-to-end
    // =========================================================================

    @Nested
    class EndToEnd {

        @Test
        void fileHandleProtocol() {
            var config = TestGenConfig.withDefaults("FileHandle");
            var out = generate("open . &{read: close . end, write: close . end}", config);
            assertTrue(out.contains("class FileHandleProtocolTest"));
            assertTrue(out.contains("validPath_open_read_close"));
            assertTrue(out.contains("validPath_open_write_close"));
            assertTrue(out.contains("Valid paths (2)"));
        }

        @Test
        void recursiveIterator() {
            var config = new TestGenConfig("Iter", "com.example", "obj", 1, 100, ViolationStyle.DISABLED_ANNOTATION);
            var out = generate("rec X . &{next: X, done: end}", config);
            assertTrue(out.contains("package com.example;"));
            assertTrue(out.contains("class IterProtocolTest"));
            assertTrue(out.contains("validPath_done"));
            assertTrue(out.contains("validPath_next_done"));
        }

        @Test
        void callAnywayEndToEnd() {
            var config = new TestGenConfig("Conn", null, "c", 2, 100, ViolationStyle.CALL_ANYWAY);
            var out = generate("open . close . end", config);
            assertTrue(out.contains("Conn c = new Conn()"));
            assertTrue(out.contains("assertThrows"));
        }

        @Test
        void selectProtocol_topLevel() {
            // +{OK: a.end, ERR: end} — top-level selection, no method to switch on
            // Each branch becomes a separate program
            var out = generate("+{OK: a.end, ERR: end}");
            assertTrue(out.contains("Valid paths (2)"));
        }

        @Test
        void selectStepsEmittedAsSwitchStatements() {
            var out = generate("m . +{OK: end, ERR: end}");
            assertTrue(out.contains("var mResult = obj.m()"),
                    "Selection-returning method should use var declaration");
            assertTrue(out.contains("switch (mResult)"),
                    "Result should be checked with switch");
            assertTrue(out.contains("case OK ->"),
                    "Switch should have case for OK");
            assertTrue(out.contains("case ERR ->"),
                    "Switch should have case for ERR");
            // Only 1 valid path (the switch covers both outcomes)
            assertTrue(out.contains("Valid paths (1)"));
        }

        @Test
        void selectProtocol_noViolationsForSelectionLabels() {
            var out = generate("+{OK: end, ERR: end}");
            assertTrue(out.contains("Violations (0)"),
                    "Pure selection should have no violations");
        }

        @Test
        void selectionWithSubBranches() {
            // m . +{A: &{x: end, y: end}, B: end} → 2 switch programs
            var out = generate("m . +{A: &{x: end, y: end}, B: end}");
            assertTrue(out.contains("Valid paths (2)"));
            assertTrue(out.contains("var mResult = obj.m()"));
            assertTrue(out.contains("case A ->"));
            assertTrue(out.contains("case B ->"));
        }

        @Test
        void nestedSwitchGeneration() {
            // m . +{A: n . +{X: end, Y: end}, B: end} → nested switch
            var out = generate("m . +{A: n . +{X: end, Y: end}, B: end}");
            assertTrue(out.contains("var mResult = obj.m()"));
            assertTrue(out.contains("var nResult = obj.n()"));
            assertTrue(out.contains("case X ->"));
            assertTrue(out.contains("case Y ->"));
        }

        @Test
        void recursiveSwitchVariableNames() {
            // rec X . m . +{A: X, B: end} → nested switch, variable names: mResult, mResult2
            var config = new TestGenConfig("Obj", null, "obj", 1, 100, ViolationStyle.DISABLED_ANNOTATION);
            var out = generate("rec X . m . +{A: X, B: end}", config);
            assertTrue(out.contains("var mResult = obj.m()"));
            assertTrue(out.contains("var mResult2 = obj.m()"));
        }

        @Test
        void outputIsCompilableStructure() {
            // Basic structural check: balanced braces
            var out = generate("open . &{read: close . end, write: close . end}");
            long openBraces = out.chars().filter(c -> c == '{').count();
            long closeBraces = out.chars().filter(c -> c == '}').count();
            assertEquals(openBraces, closeBraces, "Braces should be balanced");
        }

        @Test
        void switchStatementBalancedBraces() {
            var out = generate("m . +{OK: end, ERR: end}");
            long openBraces = out.chars().filter(c -> c == '{').count();
            long closeBraces = out.chars().filter(c -> c == '}').count();
            assertEquals(openBraces, closeBraces, "Braces should be balanced in switch output");
        }
    }

    // =========================================================================
    // Config
    // =========================================================================

    @Nested
    class ConfigTests {

        @Test
        void withDefaultsFactory() {
            var config = TestGenConfig.withDefaults("Foo");
            assertEquals("Foo", config.className());
            assertNull(config.packageName());
            assertEquals("obj", config.varName());
            assertEquals(2, config.maxRevisits());
            assertEquals(100, config.maxPaths());
            assertEquals(ViolationStyle.DISABLED_ANNOTATION, config.violationStyle());
        }

        @Test
        void withPackageFactory() {
            var config = TestGenConfig.withPackage("Bar", "com.test");
            assertEquals("Bar", config.className());
            assertEquals("com.test", config.packageName());
        }

        @Test
        void nullClassNameThrows() {
            assertThrows(NullPointerException.class,
                    () -> TestGenConfig.withDefaults(null));
        }

        @Test
        void blankClassNameThrows() {
            assertThrows(IllegalArgumentException.class,
                    () -> TestGenConfig.withDefaults("  "));
        }

        @Test
        void negativeMaxRevisitsThrows() {
            assertThrows(IllegalArgumentException.class,
                    () -> new TestGenConfig("X", null, "obj", -1, 100, ViolationStyle.DISABLED_ANNOTATION));
        }

        @Test
        void zeroMaxPathsThrows() {
            assertThrows(IllegalArgumentException.class,
                    () -> new TestGenConfig("X", null, "obj", 2, 0, ViolationStyle.DISABLED_ANNOTATION));
        }

        @Test
        void nullVarNameDefaultsToObj() {
            var config = new TestGenConfig("X", null, null, 2, 100, ViolationStyle.DISABLED_ANNOTATION);
            assertEquals("obj", config.varName());
        }

        @Test
        void nullViolationStyleDefaultsToDisabled() {
            var config = new TestGenConfig("X", null, "obj", 2, 100, null);
            assertEquals(ViolationStyle.DISABLED_ANNOTATION, config.violationStyle());
        }
    }
}
