package com.bica.reborn.samples;

import com.bica.reborn.exception.ProtocolViolationException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Protocol conformance tests for ATM.
 * Session type: insertCard . enterPIN . +{AUTH: rec X . &{checkBalance: X, withdraw: +{OK: X, INSUFFICIENT: X}, deposit: X, ejectCard: end}, REJECTED: ejectCard . end}
 * Generated by BICA Reborn test generator.
 */
class ATMProtocolTest {

    // ===== Valid paths (22) =====

    @Test
    void validPath_insertCard_enterPIN_checkBalance_checkBalance_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                obj.checkBalance();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                    }
                    case INSUFFICIENT -> {
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_checkBalance_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                obj.checkBalance();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_withdraw_withdraw_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        var withdrawResult3 = obj.withdraw();
                        switch (withdrawResult3) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_withdraw_ejectCard_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.ejectCard();
                    }
                    case INSUFFICIENT -> {
                        obj.ejectCard();
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_deposit_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                obj.deposit();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                    }
                    case INSUFFICIENT -> {
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_deposit_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                obj.deposit();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_checkBalance_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.checkBalance();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_checkBalance_withdraw_checkBalance_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.checkBalance();
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        obj.checkBalance();
                        var withdrawResult3 = obj.withdraw();
                        switch (withdrawResult3) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_checkBalance_ejectCard_checkBalance_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.checkBalance();
                        obj.ejectCard();
                    }
                    case INSUFFICIENT -> {
                        obj.checkBalance();
                        obj.ejectCard();
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_withdraw_withdraw_withdraw_withdraw_withdraw_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                                var withdrawResult3 = obj.withdraw();
                                switch (withdrawResult3) {
                                    case OK -> {
                                    }
                                    case INSUFFICIENT -> {
                                    }
                                }
                            }
                            case INSUFFICIENT -> {
                                var withdrawResult4 = obj.withdraw();
                                switch (withdrawResult4) {
                                    case OK -> {
                                    }
                                    case INSUFFICIENT -> {
                                    }
                                }
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        var withdrawResult5 = obj.withdraw();
                        switch (withdrawResult5) {
                            case OK -> {
                                var withdrawResult6 = obj.withdraw();
                                switch (withdrawResult6) {
                                    case OK -> {
                                    }
                                    case INSUFFICIENT -> {
                                    }
                                }
                            }
                            case INSUFFICIENT -> {
                                var withdrawResult7 = obj.withdraw();
                                switch (withdrawResult7) {
                                    case OK -> {
                                    }
                                    case INSUFFICIENT -> {
                                    }
                                }
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_withdraw_ejectCard_ejectCard_withdraw_ejectCard_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                                obj.ejectCard();
                            }
                            case INSUFFICIENT -> {
                                obj.ejectCard();
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        var withdrawResult3 = obj.withdraw();
                        switch (withdrawResult3) {
                            case OK -> {
                                obj.ejectCard();
                            }
                            case INSUFFICIENT -> {
                                obj.ejectCard();
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_deposit_withdraw_deposit_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.deposit();
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        obj.deposit();
                        var withdrawResult3 = obj.withdraw();
                        switch (withdrawResult3) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_deposit_ejectCard_deposit_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.deposit();
                        obj.ejectCard();
                    }
                    case INSUFFICIENT -> {
                        obj.deposit();
                        obj.ejectCard();
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_withdraw_ejectCard_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.ejectCard();
                    }
                    case INSUFFICIENT -> {
                        obj.ejectCard();
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_checkBalance_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                obj.checkBalance();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                    }
                    case INSUFFICIENT -> {
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_checkBalance_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                obj.checkBalance();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_withdraw_withdraw_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        var withdrawResult2 = obj.withdraw();
                        switch (withdrawResult2) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                    case INSUFFICIENT -> {
                        var withdrawResult3 = obj.withdraw();
                        switch (withdrawResult3) {
                            case OK -> {
                            }
                            case INSUFFICIENT -> {
                            }
                        }
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_withdraw_ejectCard_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                        obj.ejectCard();
                    }
                    case INSUFFICIENT -> {
                        obj.ejectCard();
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_deposit_withdraw_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                obj.deposit();
                var withdrawResult = obj.withdraw();
                switch (withdrawResult) {
                    case OK -> {
                    }
                    case INSUFFICIENT -> {
                    }
                }
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_deposit_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                obj.deposit();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_deposit_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.deposit();
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    @Test
    void validPath_insertCard_enterPIN_ejectCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        var enterPINResult = obj.enterPIN();
        switch (enterPINResult) {
            case AUTH -> {
                obj.ejectCard();
            }
            case REJECTED -> {
                obj.ejectCard();
            }
        }
    }

    // ===== Violations (17) =====

    @Test
    void violation_initial_checkBalance() {
        ATM obj = new ATM();
        assertThrows(ProtocolViolationException.class, () -> obj.checkBalance());
    }

    @Test
    void violation_initial_deposit() {
        ATM obj = new ATM();
        assertThrows(ProtocolViolationException.class, () -> obj.deposit());
    }

    @Test
    void violation_initial_ejectCard() {
        ATM obj = new ATM();
        assertThrows(ProtocolViolationException.class, () -> obj.ejectCard());
    }

    @Test
    void violation_initial_enterPIN() {
        ATM obj = new ATM();
        assertThrows(ProtocolViolationException.class, () -> obj.enterPIN());
    }

    @Test
    void violation_initial_withdraw() {
        ATM obj = new ATM();
        assertThrows(ProtocolViolationException.class, () -> obj.withdraw());
    }

    @Test
    void violation_insertCard_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        assertThrows(ProtocolViolationException.class, () -> obj.checkBalance());
    }

    @Test
    void violation_insertCard_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        assertThrows(ProtocolViolationException.class, () -> obj.deposit());
    }

    @Test
    void violation_insertCard_ejectCard() {
        ATM obj = new ATM();
        obj.insertCard();
        assertThrows(ProtocolViolationException.class, () -> obj.ejectCard());
    }

    @Test
    void violation_insertCard_insertCard() {
        ATM obj = new ATM();
        obj.insertCard();
        assertThrows(ProtocolViolationException.class, () -> obj.insertCard());
    }

    @Test
    void violation_insertCard_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        assertThrows(ProtocolViolationException.class, () -> obj.withdraw());
    }

    @Test
    void violation_insertCard_enterPIN_AUTH_enterPIN() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.enterPIN());
    }

    @Test
    void violation_insertCard_enterPIN_AUTH_insertCard() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.insertCard());
    }

    @Test
    void violation_insertCard_enterPIN_REJECTED_checkBalance() {
        ATM obj = new ATM();
        obj.setPinValid(false);
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.checkBalance());
    }

    @Test
    void violation_insertCard_enterPIN_REJECTED_deposit() {
        ATM obj = new ATM();
        obj.setPinValid(false);
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.deposit());
    }

    @Test
    void violation_insertCard_enterPIN_REJECTED_enterPIN() {
        ATM obj = new ATM();
        obj.setPinValid(false);
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.enterPIN());
    }

    @Test
    void violation_insertCard_enterPIN_REJECTED_insertCard() {
        ATM obj = new ATM();
        obj.setPinValid(false);
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.insertCard());
    }

    @Test
    void violation_insertCard_enterPIN_REJECTED_withdraw() {
        ATM obj = new ATM();
        obj.setPinValid(false);
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.withdraw());
    }

    // ===== Incomplete protocols (29) =====

    @Disabled("Incomplete: object not in terminal state after [insertCard]")
    @Test
    void incomplete_insertCard() {
        ATM obj = new ATM();
        obj.insertCard();
        // NOT COMPLETE: enabled methods remain: [enterPIN]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN]")
    @Test
    void incomplete_insertCard_enterPIN() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // NOT COMPLETE: enabled methods remain: [AUTH, REJECTED]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance, checkBalance]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        obj.checkBalance();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance, withdraw]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        obj.withdraw();
        // NOT COMPLETE: enabled methods remain: [INSUFFICIENT, OK]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance, withdraw, OK]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance_withdraw_OK() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        obj.withdraw();
        // -> OK (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance, withdraw, INSUFFICIENT]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance_withdraw_INSUFFICIENT() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, checkBalance, deposit]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_checkBalance_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.checkBalance();
        obj.deposit();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // NOT COMPLETE: enabled methods remain: [INSUFFICIENT, OK]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK, checkBalance]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        obj.checkBalance();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK, withdraw]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        obj.withdraw();
        // NOT COMPLETE: enabled methods remain: [INSUFFICIENT, OK]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK, withdraw, OK]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK_withdraw_OK() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK, withdraw, INSUFFICIENT]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK_withdraw_INSUFFICIENT() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, OK, deposit]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_OK_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        obj.deposit();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT, checkBalance]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        obj.checkBalance();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT, withdraw]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        obj.withdraw();
        // NOT COMPLETE: enabled methods remain: [INSUFFICIENT, OK]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT, withdraw, OK]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT_withdraw_OK() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        obj.withdraw();
        // -> OK (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT, withdraw, INSUFFICIENT]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT_withdraw_INSUFFICIENT() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, withdraw, INSUFFICIENT, deposit]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_withdraw_INSUFFICIENT_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        obj.deposit();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit, checkBalance]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit_checkBalance() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        obj.checkBalance();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit, withdraw]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit_withdraw() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        obj.withdraw();
        // NOT COMPLETE: enabled methods remain: [INSUFFICIENT, OK]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit, withdraw, OK]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit_withdraw_OK() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        obj.withdraw();
        // -> OK (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit, withdraw, INSUFFICIENT]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit_withdraw_INSUFFICIENT() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        obj.withdraw();
        // -> INSUFFICIENT (selected by object)
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, AUTH, deposit, deposit]")
    @Test
    void incomplete_insertCard_enterPIN_AUTH_deposit_deposit() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> AUTH (selected by object)
        obj.deposit();
        obj.deposit();
        // NOT COMPLETE: enabled methods remain: [checkBalance, deposit, ejectCard, withdraw]
    }

    @Disabled("Incomplete: object not in terminal state after [insertCard, enterPIN, REJECTED]")
    @Test
    void incomplete_insertCard_enterPIN_REJECTED() {
        ATM obj = new ATM();
        obj.insertCard();
        obj.enterPIN();
        // -> REJECTED (selected by object)
        // NOT COMPLETE: enabled methods remain: [ejectCard]
    }
}
