package com.bica.reborn.samples;

import com.bica.reborn.exception.ProtocolViolationException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Protocol conformance tests for FileHandle.
 * Session type: open . &{read: close . end, write: close . end}
 * Generated by BICA Reborn test generator.
 */
class FileHandleProtocolTest {

    // ===== Valid paths (2) =====

    @Test
    void validPath_open_read_close() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.read();
        obj.close();
    }

    @Test
    void validPath_open_write_close() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.write();
        obj.close();
    }

    // ===== Violations (11) =====

    @Test
    void violation_initial_close() {
        FileHandle obj = new FileHandle();
        assertThrows(ProtocolViolationException.class, () -> obj.close());
    }

    @Test
    void violation_initial_read() {
        FileHandle obj = new FileHandle();
        assertThrows(ProtocolViolationException.class, () -> obj.read());
    }

    @Test
    void violation_initial_write() {
        FileHandle obj = new FileHandle();
        assertThrows(ProtocolViolationException.class, () -> obj.write());
    }

    @Test
    void violation_open_close() {
        FileHandle obj = new FileHandle();
        obj.open();
        assertThrows(ProtocolViolationException.class, () -> obj.close());
    }

    @Test
    void violation_open_open() {
        FileHandle obj = new FileHandle();
        obj.open();
        assertThrows(ProtocolViolationException.class, () -> obj.open());
    }

    @Test
    void violation_open_read_open() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.read();
        assertThrows(ProtocolViolationException.class, () -> obj.open());
    }

    @Test
    void violation_open_read_read() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.read();
        assertThrows(ProtocolViolationException.class, () -> obj.read());
    }

    @Test
    void violation_open_read_write() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.read();
        assertThrows(ProtocolViolationException.class, () -> obj.write());
    }

    @Test
    void violation_open_write_open() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.write();
        assertThrows(ProtocolViolationException.class, () -> obj.open());
    }

    @Test
    void violation_open_write_read() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.write();
        assertThrows(ProtocolViolationException.class, () -> obj.read());
    }

    @Test
    void violation_open_write_write() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.write();
        assertThrows(ProtocolViolationException.class, () -> obj.write());
    }

    // ===== Incomplete protocols (3) =====

    @Disabled("Incomplete: object not in terminal state after [open]")
    @Test
    void incomplete_open() {
        FileHandle obj = new FileHandle();
        obj.open();
        // NOT COMPLETE: enabled methods remain: [read, write]
    }

    @Disabled("Incomplete: object not in terminal state after [open, read]")
    @Test
    void incomplete_open_read() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.read();
        // NOT COMPLETE: enabled methods remain: [close]
    }

    @Disabled("Incomplete: object not in terminal state after [open, write]")
    @Test
    void incomplete_open_write() {
        FileHandle obj = new FileHandle();
        obj.open();
        obj.write();
        // NOT COMPLETE: enabled methods remain: [close]
    }
}
