package com.bica.reborn.samples;

import com.bica.reborn.exception.ProtocolViolationException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Protocol conformance tests for SimpleIterator.
 * Session type: rec X . hasNext . +{TRUE: next . X, FALSE: end}
 * Generated by BICA Reborn test generator.
 */
class SimpleIteratorProtocolTest {

    // ===== Valid paths (1) =====

    @Test
    void validPath_hasNext_next_hasNext_next_hasNext() {
        SimpleIterator obj = new SimpleIterator();
        var hasNextResult = obj.hasNext();
        switch (hasNextResult) {
            case TRUE -> {
                obj.next();
                var hasNextResult2 = obj.hasNext();
                switch (hasNextResult2) {
                    case TRUE -> {
                        obj.next();
                        var hasNextResult3 = obj.hasNext();
                        switch (hasNextResult3) {
                            case TRUE -> {
                            }
                            case FALSE -> {
                            }
                        }
                    }
                    case FALSE -> {
                    }
                }
            }
            case FALSE -> {
            }
        }
    }

    // ===== Violations (2) =====

    @Test
    void violation_initial_next() {
        SimpleIterator obj = new SimpleIterator();
        assertThrows(ProtocolViolationException.class, () -> obj.next());
    }

    @Test
    void violation_hasNext_TRUE_hasNext() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        assertThrows(ProtocolViolationException.class, () -> obj.hasNext());
    }

    // ===== Incomplete protocols (7) =====

    @Disabled("Incomplete: object not in terminal state after [hasNext]")
    @Test
    void incomplete_hasNext() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // NOT COMPLETE: enabled methods remain: [FALSE, TRUE]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE]")
    @Test
    void incomplete_hasNext_TRUE() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        // NOT COMPLETE: enabled methods remain: [next]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE, next]")
    @Test
    void incomplete_hasNext_TRUE_next() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        // NOT COMPLETE: enabled methods remain: [hasNext]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE, next, hasNext]")
    @Test
    void incomplete_hasNext_TRUE_next_hasNext() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        obj.hasNext();
        // NOT COMPLETE: enabled methods remain: [FALSE, TRUE]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE, next, hasNext, TRUE]")
    @Test
    void incomplete_hasNext_TRUE_next_hasNext_TRUE() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        obj.hasNext();
        // -> TRUE (selected by object)
        // NOT COMPLETE: enabled methods remain: [next]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE, next, hasNext, TRUE, next]")
    @Test
    void incomplete_hasNext_TRUE_next_hasNext_TRUE_next() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        // NOT COMPLETE: enabled methods remain: [hasNext]
    }

    @Disabled("Incomplete: object not in terminal state after [hasNext, TRUE, next, hasNext, TRUE, next, hasNext]")
    @Test
    void incomplete_hasNext_TRUE_next_hasNext_TRUE_next_hasNext() {
        SimpleIterator obj = new SimpleIterator();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        obj.hasNext();
        // -> TRUE (selected by object)
        obj.next();
        obj.hasNext();
        // NOT COMPLETE: enabled methods remain: [FALSE, TRUE]
    }
}
