package com.bica.reborn.lattice;

import com.bica.reborn.lattice.DistributivityChecker.QuotientPoset;
import com.bica.reborn.statespace.StateSpace;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Prime ideal spectrum {@code Spec(L)} of a session type lattice (Step 363h).
 *
 * <p>Given a session type {@code S} with state space {@code L(S)}, this class
 * constructs the prime ideal spectrum {@code Spec(L(S))} together with a
 * Zariski-style topology generated by basic open sets
 * {@code D(a) = {p ∈ Spec(L) : a ∉ p}}.
 *
 * <p>The construction works on the SCC quotient of the state space (so cycles
 * from recursive types are collapsed) and proceeds in three phases:
 * <ol>
 *   <li>Build a self-contained finite-lattice carrier (elements = SCC quotient
 *       nodes; order, meet and join tables).</li>
 *   <li>Enumerate all order-ideals (downsets closed under finite joins). For
 *       finite lattices there are at most {@code 2^|L|} of them.</li>
 *   <li>Filter to keep only the {@code prime} ideals: {@code I != L} and
 *       {@code x ∧ y ∈ I ⟹ x ∈ I ∨ y ∈ I}.</li>
 * </ol>
 *
 * <p>The Zariski-style topology has basic opens {@code D(a)} and closed sets
 * {@code V(a) = Spec(L) \ D(a) = {p : a ∈ p}}.
 *
 * <p><b>Bidirectional morphisms:</b>
 * <pre>
 *   phi : L  --&gt; Spec(L)        a |--&gt; D(a)             (Stone map)
 *   psi : Spec(L) --&gt; L          p |--&gt; bigvee (L \ p)
 * </pre>
 * For distributive {@code L} this pair classifies as an order isomorphism onto
 * the basic-open lattice and a Galois connection between {@code 2^Spec(L)} and
 * {@code L}. For non-distributive {@code L}, {@code phi} is still
 * order-preserving and {@code psi} still well defined; we report which axioms
 * hold.
 *
 * <p><b>Complexity:</b> ideal enumeration is {@code O(2^|L|)} where {@code |L|}
 * is the size of the SCC quotient; suitable for state spaces with up to a few
 * dozen states.
 *
 * <p>Ported from {@code reticulate/reticulate/prime_spectrum.py}.
 */
public final class PrimeSpectrum {

    private PrimeSpectrum() {}

    // -- Internal lattice carrier ---------------------------------------------

    /**
     * Self-contained finite lattice built from a state space's SCC quotient.
     * Elements are quotient-node indices. The order is {@code a <= b} iff
     * {@code b} reaches {@code a} in the original state space (i.e. {@code a}
     * is "later" in the protocol; bottom = end state).
     */
    static final class Lattice {
        final List<Integer> elements;
        final Map<Long, Boolean> le;
        final Map<Long, Integer> meet;
        final Map<Long, Integer> join;
        final int top;
        final int bottom;
        final Map<Integer, Integer> rep;
        final Map<Integer, Integer> stateToNode;

        Lattice(List<Integer> elements,
                Map<Long, Boolean> le,
                Map<Long, Integer> meet,
                Map<Long, Integer> join,
                int top,
                int bottom,
                Map<Integer, Integer> rep,
                Map<Integer, Integer> stateToNode) {
            this.elements = List.copyOf(elements);
            this.le = Map.copyOf(le);
            this.meet = Map.copyOf(meet);
            this.join = Map.copyOf(join);
            this.top = top;
            this.bottom = bottom;
            this.rep = Map.copyOf(rep);
            this.stateToNode = Map.copyOf(stateToNode);
        }

        static long key(int a, int b) {
            return (((long) a) << 32) | (b & 0xffffffffL);
        }

        public boolean isLe(int a, int b) {
            return le.getOrDefault(key(a, b), false);
        }

        public boolean isLt(int a, int b) {
            return a != b && isLe(a, b);
        }

        public int meetOf(int a, int b) {
            return meet.get(key(a, b));
        }

        public int joinOf(int a, int b) {
            return join.get(key(a, b));
        }

        public List<Integer> elements() { return elements; }
        public int top() { return top; }
        public int bottom() { return bottom; }
    }

    /**
     * Build a self-contained {@link Lattice} from a state space.
     *
     * @throws IllegalArgumentException if {@code ss} is not a lattice.
     */
    static Lattice buildLattice(StateSpace ss) {
        LatticeResult lr = LatticeChecker.checkLattice(ss);
        if (!lr.isLattice()) {
            throw new IllegalArgumentException(
                    "state space is not a lattice: counterexample=" + lr.counterexample());
        }

        QuotientPoset q = QuotientPoset.build(ss);
        List<Integer> nodes = new ArrayList<>(q.nodes());
        Collections.sort(nodes);

        Map<Long, Boolean> le = new HashMap<>();
        for (int a : nodes) {
            for (int b : nodes) {
                // a <= b iff b reaches a (Python convention)
                le.put(Lattice.key(a, b), q.fwdReach().get(b).contains(a));
            }
        }

        Map<Long, Integer> meet = new HashMap<>();
        Map<Long, Integer> join = new HashMap<>();
        for (int a : nodes) {
            for (int b : nodes) {
                Integer m = q.meet(a, b);
                Integer j = q.join(a, b);
                if (m == null || j == null) {
                    throw new IllegalArgumentException(
                            "missing meet/join for (" + a + "," + b + "); not a lattice");
                }
                meet.put(Lattice.key(a, b), m);
                join.put(Lattice.key(a, b), j);
            }
        }

        return new Lattice(nodes, le, meet, join, q.top(), q.bottom(),
                new HashMap<>(q.rep()), new HashMap<>(q.stateToNode()));
    }

    // -- Public result types ---------------------------------------------------

    /**
     * A prime ideal of a finite lattice.
     *
     * <p>Stored as an immutable set of quotient-node indices. Includes whether
     * the ideal is principal (generated by a single element via the down-set
     * operator) and the generator if so.
     */
    public record PrimeIdeal(Set<Integer> members, boolean isPrincipal, Integer generator) {

        public PrimeIdeal {
            members = Set.copyOf(members);
        }

        public boolean contains(int element) {
            return members.contains(element);
        }
    }

    /**
     * Zariski-style topology on {@code Spec(L)}.
     *
     * <p>Stored as the family of basic opens {@code D(a)} and the closed sets
     * {@code V(a) = Spec(L) \ D(a)}, both keyed by lattice element. For finite
     * lattices the basic opens are closed under finite intersection
     * ({@code D(a) ∩ D(b) = D(a ∧ b)}) and the basic-open family forms a
     * sub-lattice of the topology.
     */
    public record ZariskiTopology(
            List<PrimeIdeal> primes,
            Map<Integer, Set<Integer>> basicOpens,
            Map<Integer, Set<Integer>> closedSets) {

        public ZariskiTopology {
            primes = List.copyOf(primes);
            Map<Integer, Set<Integer>> bo = new LinkedHashMap<>();
            for (var e : basicOpens.entrySet()) bo.put(e.getKey(), Set.copyOf(e.getValue()));
            basicOpens = Collections.unmodifiableMap(bo);
            Map<Integer, Set<Integer>> cs = new LinkedHashMap<>();
            for (var e : closedSets.entrySet()) cs.put(e.getKey(), Set.copyOf(e.getValue()));
            closedSets = Collections.unmodifiableMap(cs);
        }

        public int numPoints() { return primes.size(); }

        public Set<Integer> openOf(int element) { return basicOpens.get(element); }

        public Set<Integer> closedOf(int element) { return closedSets.get(element); }
    }

    /** Full result of a {@code Spec(L)} computation. */
    public record SpectrumResult(
            boolean isLattice,
            boolean isDistributive,
            int numElements,
            int numIdeals,
            int numPrimeIdeals,
            List<PrimeIdeal> primes,
            ZariskiTopology topology,
            List<Set<Integer>> irreducibleComponents,
            boolean phiIsOrderPreserving,
            boolean phiIsInjective,
            boolean psiIsWellDefined,
            boolean dualityHolds,
            List<String> notes) {

        public SpectrumResult {
            primes = List.copyOf(primes);
            List<Set<Integer>> ic = new ArrayList<>();
            for (Set<Integer> c : irreducibleComponents) ic.add(Set.copyOf(c));
            irreducibleComponents = Collections.unmodifiableList(ic);
            notes = List.copyOf(notes);
        }

        /** A protocol is irreducible iff {@code Spec(L)} is connected. */
        public boolean isIrreducible() {
            return irreducibleComponents.size() <= 1;
        }
    }

    // -- Ideal / prime-ideal enumeration --------------------------------------

    /**
     * Enumerate all order-ideals of {@code L}.
     *
     * <p>An order-ideal is a downset closed under finite joins. By convention
     * every ideal of a bounded lattice contains bottom (the empty set is
     * excluded). Walks the powerset of {@code L}; complexity {@code O(2^|L|)}.
     */
    public static List<Set<Integer>> enumerateIdeals(Lattice L) {
        List<Integer> elements = L.elements();
        int n = elements.size();
        List<Set<Integer>> ideals = new ArrayList<>();

        for (int mask = 0; mask < (1 << n); mask++) {
            List<Integer> subsetList = new ArrayList<>();
            Set<Integer> subset = new HashSet<>();
            for (int i = 0; i < n; i++) {
                if ((mask & (1 << i)) != 0) {
                    subsetList.add(elements.get(i));
                    subset.add(elements.get(i));
                }
            }

            if (!subset.contains(L.bottom())) continue;

            // Downward closed
            boolean ok = true;
            outer:
            for (int x : subsetList) {
                for (int y : elements) {
                    if (L.isLe(y, x) && !subset.contains(y)) {
                        ok = false;
                        break outer;
                    }
                }
            }
            if (!ok) continue;

            // Closed under join
            boolean joinClosed = true;
            outer2:
            for (int x : subsetList) {
                for (int y : subsetList) {
                    if (!subset.contains(L.joinOf(x, y))) {
                        joinClosed = false;
                        break outer2;
                    }
                }
            }
            if (!joinClosed) continue;

            ideals.add(Set.copyOf(subset));
        }

        return ideals;
    }

    /**
     * Enumerate all prime ideals of {@code L}.
     *
     * <p>An ideal {@code I} is prime iff {@code I != L} and
     * {@code x ∧ y ∈ I ⟹ x ∈ I ∨ y ∈ I}.
     */
    public static List<PrimeIdeal> enumeratePrimeIdeals(Lattice L) {
        List<Set<Integer>> ideals = enumerateIdeals(L);
        Set<Integer> full = Set.copyOf(L.elements());
        List<PrimeIdeal> primes = new ArrayList<>();

        for (Set<Integer> I : ideals) {
            if (I.equals(full)) continue;
            if (I.isEmpty()) continue;

            boolean isPrime = true;
            outer:
            for (int x : L.elements()) {
                for (int y : L.elements()) {
                    int m = L.meetOf(x, y);
                    if (I.contains(m) && !I.contains(x) && !I.contains(y)) {
                        isPrime = false;
                        break outer;
                    }
                }
            }
            if (!isPrime) continue;

            // Detect principality: I = down(g) for some g
            Integer generator = null;
            for (int g : L.elements()) {
                Set<Integer> downG = new HashSet<>();
                for (int y : L.elements()) {
                    if (L.isLe(y, g)) downG.add(y);
                }
                if (downG.equals(I)) {
                    generator = g;
                    break;
                }
            }

            primes.add(new PrimeIdeal(I, generator != null, generator));
        }

        // Sort: by size, then lexicographic on sorted members
        primes.sort((p, q) -> {
            int c = Integer.compare(p.members().size(), q.members().size());
            if (c != 0) return c;
            List<Integer> pm = new ArrayList<>(p.members());
            List<Integer> qm = new ArrayList<>(q.members());
            Collections.sort(pm);
            Collections.sort(qm);
            for (int i = 0; i < pm.size(); i++) {
                int cc = Integer.compare(pm.get(i), qm.get(i));
                if (cc != 0) return cc;
            }
            return 0;
        });

        return primes;
    }

    // -- Topology --------------------------------------------------------------

    /** Build the Zariski-style topology on {@code Spec(L)}. */
    public static ZariskiTopology buildTopology(Lattice L, List<PrimeIdeal> primes) {
        Set<Integer> fullIdx = new HashSet<>();
        for (int i = 0; i < primes.size(); i++) fullIdx.add(i);

        Map<Integer, Set<Integer>> basicOpens = new LinkedHashMap<>();
        Map<Integer, Set<Integer>> closedSets = new LinkedHashMap<>();
        for (int a : L.elements()) {
            Set<Integer> opn = new HashSet<>();
            for (int i = 0; i < primes.size(); i++) {
                if (!primes.get(i).contains(a)) opn.add(i);
            }
            basicOpens.put(a, opn);
            Set<Integer> cls = new HashSet<>(fullIdx);
            cls.removeAll(opn);
            closedSets.put(a, cls);
        }
        return new ZariskiTopology(primes, basicOpens, closedSets);
    }

    /**
     * Connected components of {@code Spec(L)} under the Zariski topology.
     *
     * <p>Two prime ideals are in the same component iff there is a chain of
     * non-trivial basic opens or closed sets ({@code |.| >= 2}) connecting
     * them. Computed by union-find.
     */
    public static List<Set<Integer>> irreducibleComponents(
            Lattice L, ZariskiTopology topology) {
        int n = topology.numPoints();
        int[] parent = new int[n];
        for (int i = 0; i < n; i++) parent[i] = i;

        for (int a : L.elements()) {
            unionAll(parent, topology.basicOpens().get(a));
            unionAll(parent, topology.closedSets().get(a));
        }

        Map<Integer, Set<Integer>> groups = new LinkedHashMap<>();
        for (int i = 0; i < n; i++) {
            groups.computeIfAbsent(find(parent, i), k -> new HashSet<>()).add(i);
        }
        List<Set<Integer>> result = new ArrayList<>();
        for (Set<Integer> g : groups.values()) result.add(g);
        return result;
    }

    private static int find(int[] parent, int i) {
        while (parent[i] != i) {
            parent[i] = parent[parent[i]];
            i = parent[i];
        }
        return i;
    }

    private static void union(int[] parent, int i, int j) {
        int ri = find(parent, i);
        int rj = find(parent, j);
        if (ri != rj) parent[ri] = rj;
    }

    private static void unionAll(int[] parent, Set<Integer> set) {
        if (set.size() < 2) return;
        List<Integer> ids = new ArrayList<>(new TreeSet<>(set));
        int base = ids.get(0);
        for (int k = 1; k < ids.size(); k++) {
            union(parent, base, ids.get(k));
        }
    }

    // -- Bidirectional morphisms phi and psi -----------------------------------

    /**
     * {@code phi : L --> Spec(L)}, {@code phi(a) = D(a) = {p : a not in p}}.
     */
    public static Map<Integer, Set<Integer>> phiMap(Lattice L, ZariskiTopology topology) {
        return new LinkedHashMap<>(topology.basicOpens());
    }

    /**
     * {@code psi : Spec(L) --> L}, {@code psi(p) = bigvee (L \ p)}.
     *
     * <p>The complement of a prime ideal is a non-empty prime filter, so the
     * join is well defined.
     */
    public static Map<Integer, Integer> psiMap(Lattice L, List<PrimeIdeal> primes) {
        Map<Integer, Integer> out = new LinkedHashMap<>();
        for (int i = 0; i < primes.size(); i++) {
            PrimeIdeal p = primes.get(i);
            List<Integer> complement = new ArrayList<>();
            for (int a : L.elements()) {
                if (!p.contains(a)) complement.add(a);
            }
            if (complement.isEmpty()) {
                out.put(i, L.bottom());
                continue;
            }
            int acc = complement.get(0);
            for (int k = 1; k < complement.size(); k++) {
                acc = L.joinOf(acc, complement.get(k));
            }
            out.put(i, acc);
        }
        return out;
    }

    /** Verify the bidirectional morphism axioms for {@code (phi, psi)}. */
    public static Map<String, Boolean> checkMorphisms(Lattice L, ZariskiTopology topology) {
        List<PrimeIdeal> primes = topology.primes();
        Map<Integer, Set<Integer>> phi = phiMap(L, topology);
        Map<Integer, Integer> psi = psiMap(L, primes);

        // Order preservation of phi
        boolean phiOp = true;
        outer:
        for (int a : L.elements()) {
            for (int b : L.elements()) {
                if (L.isLe(a, b) && !phi.get(b).containsAll(phi.get(a))) {
                    phiOp = false;
                    break outer;
                }
            }
        }

        // Injectivity of phi
        boolean phiInj = true;
        Map<Set<Integer>, Integer> seen = new HashMap<>();
        for (int a : L.elements()) {
            Set<Integer> img = phi.get(a);
            Integer prev = seen.get(img);
            if (prev != null && prev != a) {
                phiInj = false;
                break;
            }
            seen.put(img, a);
        }

        // psi well defined
        boolean psiWd = true;
        for (int i = 0; i < primes.size(); i++) {
            if (!psi.containsKey(i)) { psiWd = false; break; }
        }

        // Round-trip duality: i in phi[psi[i]] for every prime
        boolean duality = true;
        for (int i = 0; i < primes.size(); i++) {
            int a = psi.get(i);
            if (!phi.get(a).contains(i)) {
                duality = false;
                break;
            }
        }

        Map<String, Boolean> out = new LinkedHashMap<>();
        out.put("phi_order_preserving", phiOp);
        out.put("phi_injective", phiInj);
        out.put("psi_well_defined", psiWd);
        out.put("duality_holds", duality);
        return out;
    }

    // -- Top-level entry point -------------------------------------------------

    /** Compute the prime ideal spectrum of a state space's lattice. */
    public static SpectrumResult computeSpectrum(StateSpace ss) {
        List<String> notes = new ArrayList<>();
        Lattice L;
        try {
            L = buildLattice(ss);
        } catch (IllegalArgumentException e) {
            return new SpectrumResult(
                    false, false, 0, 0, 0,
                    List.of(), null, List.of(),
                    false, false, false, false,
                    List.of("not a lattice: " + e.getMessage()));
        }

        DistributivityResult dr = DistributivityChecker.checkDistributive(ss);

        List<Set<Integer>> ideals = enumerateIdeals(L);
        List<PrimeIdeal> primes = enumeratePrimeIdeals(L);
        ZariskiTopology topology = buildTopology(L, primes);
        List<Set<Integer>> components = irreducibleComponents(L, topology);
        Map<String, Boolean> morph = checkMorphisms(L, topology);

        if (!dr.isDistributive()) {
            notes.add("lattice is non-distributive; phi may fail to be a lattice "
                    + "homomorphism even when it remains order-preserving");
        }
        if (components.size() > 1) {
            notes.add("protocol decomposes into " + components.size()
                    + " irreducible components");
        }

        return new SpectrumResult(
                true,
                dr.isDistributive(),
                L.elements().size(),
                ideals.size(),
                primes.size(),
                primes,
                topology,
                components,
                morph.get("phi_order_preserving"),
                morph.get("phi_injective"),
                morph.get("psi_well_defined"),
                morph.get("duality_holds"),
                notes);
    }
}
