package com.bica.reborn.prime_spectrum;

import com.bica.reborn.statespace.StateSpace;

import java.util.*;

/**
 * Prime ideal spectrum Spec(L) of a session type lattice (Step 363h).
 *
 * <p>Java port of {@code reticulate/reticulate/prime_spectrum.py}. Java/Python
 * parity is mandatory for every step in the research programme.
 *
 * <p>Given a state space {@code ss}, this checker constructs the SCC-quotient
 * lattice, enumerates all order-ideals and all prime ideals, builds the
 * Zariski-style topology generated by basic open sets
 * {@code D(a) = {p in Spec : a not in p}}, computes connected components, and
 * exposes the bidirectional morphism pair
 * {@code phi(a) = D(a)} and {@code psi(p) = bigvee(L \ p)}.
 *
 * <p>See {@code papers/steps/step363h-prime-spectrum/main.tex} for theory.
 */
public final class PrimeSpectrumChecker {

    private PrimeSpectrumChecker() {}

    // -----------------------------------------------------------------------
    // Result records
    // -----------------------------------------------------------------------

    /**
     * A prime ideal of the finite lattice, stored as a sorted member list.
     *
     * @param members     elements of the ideal (quotient-node indices)
     * @param isPrincipal whether I = down(generator) for some element
     * @param generator   the generator if principal, else null
     */
    public record PrimeIdeal(
            List<Integer> members,
            boolean isPrincipal,
            Integer generator) {

        public PrimeIdeal {
            members = List.copyOf(members);
        }

        public boolean contains(int element) {
            return members.contains(element);
        }

        public Set<Integer> memberSet() {
            return new HashSet<>(members);
        }
    }

    /**
     * The Zariski-style topology on Spec(L).
     *
     * @param primes      the ordered list of prime ideals
     * @param basicOpens  element -> set of prime indices forming D(a)
     * @param closedSets  element -> set of prime indices forming V(a)
     */
    public record ZariskiTopology(
            List<PrimeIdeal> primes,
            Map<Integer, Set<Integer>> basicOpens,
            Map<Integer, Set<Integer>> closedSets) {

        public ZariskiTopology {
            primes = List.copyOf(primes);
            basicOpens = Map.copyOf(basicOpens);
            closedSets = Map.copyOf(closedSets);
        }

        public int numPoints() {
            return primes.size();
        }

        public Set<Integer> openOf(int element) {
            return basicOpens.getOrDefault(element, Set.of());
        }

        public Set<Integer> closedOf(int element) {
            return closedSets.getOrDefault(element, Set.of());
        }
    }

    /**
     * Full result of a spectrum computation.
     */
    public record SpectrumResult(
            boolean isLattice,
            int numElements,
            int numIdeals,
            int numPrimeIdeals,
            List<PrimeIdeal> primes,
            ZariskiTopology topology,
            List<Set<Integer>> irreducibleComponents,
            boolean phiIsOrderPreserving,
            boolean phiIsInjective,
            boolean psiIsWellDefined,
            boolean dualityHolds,
            List<String> notes) {

        public SpectrumResult {
            primes = List.copyOf(primes);
            irreducibleComponents = List.copyOf(irreducibleComponents);
            notes = List.copyOf(notes);
        }

        public boolean isIrreducible() {
            return irreducibleComponents.size() <= 1;
        }
    }

    // -----------------------------------------------------------------------
    // Internal lattice carrier
    // -----------------------------------------------------------------------

    static final class LatticeCarrier {
        public final List<Integer> elements;              // sorted quotient node ids
        public final int[][] meet;                        // meet[i][j] indexed by position in `elements`
        public final int[][] join;
        public final boolean[][] le;
        public final int topIdx;
        public final int bottomIdx;
        public final Map<Integer, Integer> nodeToIndex;   // quotient node id -> position

        LatticeCarrier(List<Integer> elements,
                       int[][] meet, int[][] join, boolean[][] le,
                       int topIdx, int bottomIdx,
                       Map<Integer, Integer> nodeToIndex) {
            this.elements = elements;
            this.meet = meet;
            this.join = join;
            this.le = le;
            this.topIdx = topIdx;
            this.bottomIdx = bottomIdx;
            this.nodeToIndex = nodeToIndex;
        }

        int size() { return elements.size(); }
    }

    // -----------------------------------------------------------------------
    // Top-level entry point
    // -----------------------------------------------------------------------

    public static SpectrumResult computeSpectrum(StateSpace ss) {
        LatticeCarrier L;
        try {
            L = buildLattice(ss);
        } catch (IllegalArgumentException e) {
            return new SpectrumResult(
                    false, 0, 0, 0, List.of(), null, List.of(),
                    false, false, false, false,
                    List.of("not a lattice: " + e.getMessage()));
        }

        List<Set<Integer>> ideals = enumerateIdeals(L);
        List<PrimeIdeal> primes = enumeratePrimeIdeals(L, ideals);
        ZariskiTopology topology = buildTopology(L, primes);
        List<Set<Integer>> components = irreducibleComponents(L, topology);
        Map<String, Boolean> morph = checkMorphisms(L, topology);

        List<String> notes = new ArrayList<>();
        if (components.size() > 1) {
            notes.add("protocol decomposes into " + components.size()
                    + " irreducible components");
        }

        return new SpectrumResult(
                true,
                L.size(),
                ideals.size(),
                primes.size(),
                primes,
                topology,
                components,
                morph.get("phi_order_preserving"),
                morph.get("phi_injective"),
                morph.get("psi_well_defined"),
                morph.get("duality_holds"),
                notes);
    }

    // -----------------------------------------------------------------------
    // Lattice construction (self-contained SCC quotient)
    // -----------------------------------------------------------------------

    static LatticeCarrier buildLattice(StateSpace ss) {
        // --- SCC quotient ---
        Map<Integer, List<Integer>> adj = new HashMap<>();
        for (int s : ss.states()) adj.put(s, new ArrayList<>());
        for (var t : ss.transitions()) adj.get(t.source()).add(t.target());

        List<Set<Integer>> sccs = computeSccs(ss.states(), adj);
        Map<Integer, Integer> stateToScc = new HashMap<>();
        for (int i = 0; i < sccs.size(); i++) {
            for (int s : sccs.get(i)) stateToScc.put(s, i);
        }
        int n = sccs.size();
        List<Integer> nodes = new ArrayList<>();
        for (int i = 0; i < n; i++) nodes.add(i);

        // --- Quotient adjacency ---
        List<Set<Integer>> fwdAdj = new ArrayList<>();
        for (int i = 0; i < n; i++) fwdAdj.add(new HashSet<>());
        for (var t : ss.transitions()) {
            int s = stateToScc.get(t.source());
            int q = stateToScc.get(t.target());
            if (s != q) fwdAdj.get(s).add(q);
        }

        // --- Forward reachability ---
        List<Set<Integer>> fwdReach = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            Set<Integer> r = new HashSet<>();
            r.add(i);
            fwdReach.add(r);
        }
        // DFS-based closure
        for (int i = 0; i < n; i++) {
            Deque<Integer> stack = new ArrayDeque<>();
            Set<Integer> seen = new HashSet<>();
            stack.push(i);
            while (!stack.isEmpty()) {
                int v = stack.pop();
                if (!seen.add(v)) continue;
                fwdReach.get(i).add(v);
                for (int w : fwdAdj.get(v)) stack.push(w);
            }
        }
        // Reverse reachability
        List<Set<Integer>> revReach = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            Set<Integer> r = new HashSet<>();
            r.add(i);
            revReach.add(r);
        }
        for (int i = 0; i < n; i++) {
            for (int j : fwdReach.get(i)) revReach.get(j).add(i);
        }

        int qTop = stateToScc.get(ss.top());
        int qBottom = stateToScc.get(ss.bottom());

        // --- Order, meet, join tables (indexed by position in nodes list) ---
        boolean[][] le = new boolean[n][n];
        int[][] meet = new int[n][n];
        int[][] join = new int[n][n];
        Map<Integer, Integer> nodeToIndex = new HashMap<>();
        for (int i = 0; i < n; i++) nodeToIndex.put(nodes.get(i), i);

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                // a <= b iff b reaches a (protocol order: top reaches everything)
                int a = nodes.get(i);
                int b = nodes.get(j);
                le[i][j] = fwdReach.get(b).contains(a);
            }
        }

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                int a = nodes.get(i);
                int b = nodes.get(j);
                Integer m = meetOnQuotient(a, b, fwdReach);
                Integer jj = joinOnQuotient(a, b, revReach);
                if (m == null || jj == null) {
                    throw new IllegalArgumentException(
                            "missing meet/join for (" + a + "," + b + ")");
                }
                meet[i][j] = nodeToIndex.get(m);
                join[i][j] = nodeToIndex.get(jj);
            }
        }

        int topIdx = nodeToIndex.get(qTop);
        int bottomIdx = nodeToIndex.get(qBottom);
        return new LatticeCarrier(nodes, meet, join, le, topIdx, bottomIdx, nodeToIndex);
    }

    private static Integer meetOnQuotient(int a, int b, List<Set<Integer>> fwdReach) {
        if (a == b) return a;
        Set<Integer> lowerBounds = new HashSet<>(fwdReach.get(a));
        lowerBounds.retainAll(fwdReach.get(b));
        if (lowerBounds.isEmpty()) return null;
        for (int m : lowerBounds) {
            if (fwdReach.get(m).containsAll(lowerBounds)) return m;
        }
        return null;
    }

    private static Integer joinOnQuotient(int a, int b, List<Set<Integer>> revReach) {
        if (a == b) return a;
        Set<Integer> upperBounds = new HashSet<>(revReach.get(a));
        upperBounds.retainAll(revReach.get(b));
        if (upperBounds.isEmpty()) return null;
        for (int j : upperBounds) {
            if (revReach.get(j).containsAll(upperBounds)) return j;
        }
        return null;
    }

    private static List<Set<Integer>> computeSccs(
            Set<Integer> states, Map<Integer, List<Integer>> adj) {
        int[] indexCounter = {0};
        Deque<Integer> stack = new ArrayDeque<>();
        Set<Integer> onStack = new HashSet<>();
        Map<Integer, Integer> index = new HashMap<>();
        Map<Integer, Integer> lowlink = new HashMap<>();
        List<Set<Integer>> result = new ArrayList<>();

        List<Integer> sorted = new ArrayList<>(states);
        Collections.sort(sorted);
        for (int start : sorted) {
            if (index.containsKey(start)) continue;
            Deque<int[]> callStack = new ArrayDeque<>();
            index.put(start, indexCounter[0]);
            lowlink.put(start, indexCounter[0]);
            indexCounter[0]++;
            stack.push(start);
            onStack.add(start);
            callStack.push(new int[]{start, 0});
            while (!callStack.isEmpty()) {
                int[] frame = callStack.peek();
                int v = frame[0];
                int ni = frame[1];
                List<Integer> neighbors = adj.getOrDefault(v, List.of());
                if (ni < neighbors.size()) {
                    frame[1] = ni + 1;
                    int w = neighbors.get(ni);
                    if (!index.containsKey(w)) {
                        index.put(w, indexCounter[0]);
                        lowlink.put(w, indexCounter[0]);
                        indexCounter[0]++;
                        stack.push(w);
                        onStack.add(w);
                        callStack.push(new int[]{w, 0});
                    } else if (onStack.contains(w)) {
                        lowlink.put(v, Math.min(lowlink.get(v), index.get(w)));
                    }
                } else {
                    if (lowlink.get(v).equals(index.get(v))) {
                        Set<Integer> sccMembers = new HashSet<>();
                        while (true) {
                            int w = stack.pop();
                            onStack.remove(w);
                            sccMembers.add(w);
                            if (w == v) break;
                        }
                        result.add(sccMembers);
                    }
                    callStack.pop();
                    if (!callStack.isEmpty()) {
                        int parent = callStack.peek()[0];
                        lowlink.put(parent,
                                Math.min(lowlink.get(parent), lowlink.get(v)));
                    }
                }
            }
        }
        return result;
    }

    // -----------------------------------------------------------------------
    // Ideal enumeration
    // -----------------------------------------------------------------------

    static List<Set<Integer>> enumerateIdeals(LatticeCarrier L) {
        int n = L.size();
        if (n > 30) {
            throw new IllegalArgumentException("lattice too large for brute enumeration: " + n);
        }
        List<Set<Integer>> ideals = new ArrayList<>();
        for (int mask = 0; mask < (1 << n); mask++) {
            Set<Integer> subset = new HashSet<>();
            for (int i = 0; i < n; i++) {
                if ((mask & (1 << i)) != 0) subset.add(i);
            }
            if (!subset.contains(L.bottomIdx)) continue;

            // Downward closed
            boolean ok = true;
            outer:
            for (int x : subset) {
                for (int y = 0; y < n; y++) {
                    if (L.le[y][x] && !subset.contains(y)) {
                        ok = false;
                        break outer;
                    }
                }
            }
            if (!ok) continue;

            // Closed under join
            boolean joinClosed = true;
            outer2:
            for (int x : subset) {
                for (int y : subset) {
                    if (!subset.contains(L.join[x][y])) {
                        joinClosed = false;
                        break outer2;
                    }
                }
            }
            if (!joinClosed) continue;

            ideals.add(subset);
        }
        return ideals;
    }

    static List<PrimeIdeal> enumeratePrimeIdeals(LatticeCarrier L, List<Set<Integer>> ideals) {
        List<PrimeIdeal> primes = new ArrayList<>();
        int n = L.size();
        Set<Integer> full = new HashSet<>();
        for (int i = 0; i < n; i++) full.add(i);

        for (Set<Integer> I : ideals) {
            if (I.equals(full) || I.isEmpty()) continue;
            boolean isPrime = true;
            outer:
            for (int x = 0; x < n; x++) {
                for (int y = 0; y < n; y++) {
                    if (I.contains(L.meet[x][y]) && !I.contains(x) && !I.contains(y)) {
                        isPrime = false;
                        break outer;
                    }
                }
            }
            if (!isPrime) continue;

            // Detect principality
            Integer generator = null;
            for (int g = 0; g < n; g++) {
                Set<Integer> downG = new HashSet<>();
                for (int y = 0; y < n; y++) {
                    if (L.le[y][g]) downG.add(y);
                }
                if (downG.equals(I)) {
                    generator = g;
                    break;
                }
            }

            List<Integer> members = new ArrayList<>(I);
            Collections.sort(members);
            primes.add(new PrimeIdeal(members, generator != null, generator));
        }

        primes.sort((a, b) -> {
            int c = Integer.compare(a.members.size(), b.members.size());
            if (c != 0) return c;
            for (int i = 0; i < a.members.size(); i++) {
                int d = Integer.compare(a.members.get(i), b.members.get(i));
                if (d != 0) return d;
            }
            return 0;
        });
        return primes;
    }

    // -----------------------------------------------------------------------
    // Topology
    // -----------------------------------------------------------------------

    static ZariskiTopology buildTopology(LatticeCarrier L, List<PrimeIdeal> primes) {
        int np = primes.size();
        Set<Integer> fullIdx = new HashSet<>();
        for (int i = 0; i < np; i++) fullIdx.add(i);

        Map<Integer, Set<Integer>> basicOpens = new HashMap<>();
        Map<Integer, Set<Integer>> closedSets = new HashMap<>();
        for (int a = 0; a < L.size(); a++) {
            Set<Integer> opn = new HashSet<>();
            for (int i = 0; i < np; i++) {
                if (!primes.get(i).members.contains(a)) opn.add(i);
            }
            basicOpens.put(a, opn);
            Set<Integer> cls = new HashSet<>(fullIdx);
            cls.removeAll(opn);
            closedSets.put(a, cls);
        }
        return new ZariskiTopology(primes, basicOpens, closedSets);
    }

    // -----------------------------------------------------------------------
    // Connected components (union-find)
    // -----------------------------------------------------------------------

    static List<Set<Integer>> irreducibleComponents(
            LatticeCarrier L, ZariskiTopology topology) {
        int n = topology.primes.size();
        int[] parent = new int[n];
        for (int i = 0; i < n; i++) parent[i] = i;

        for (int a = 0; a < L.size(); a++) {
            Set<Integer> opn = topology.basicOpens.get(a);
            if (opn.size() >= 2) {
                List<Integer> ids = new ArrayList<>(opn);
                Collections.sort(ids);
                int base = ids.get(0);
                for (int i = 1; i < ids.size(); i++) union(parent, base, ids.get(i));
            }
            Set<Integer> cls = topology.closedSets.get(a);
            if (cls.size() >= 2) {
                List<Integer> ids = new ArrayList<>(cls);
                Collections.sort(ids);
                int base = ids.get(0);
                for (int i = 1; i < ids.size(); i++) union(parent, base, ids.get(i));
            }
        }

        Map<Integer, Set<Integer>> groups = new HashMap<>();
        for (int i = 0; i < n; i++) {
            groups.computeIfAbsent(find(parent, i), k -> new HashSet<>()).add(i);
        }
        return new ArrayList<>(groups.values());
    }

    private static int find(int[] parent, int i) {
        while (parent[i] != i) {
            parent[i] = parent[parent[i]];
            i = parent[i];
        }
        return i;
    }

    private static void union(int[] parent, int a, int b) {
        int ra = find(parent, a);
        int rb = find(parent, b);
        if (ra != rb) parent[ra] = rb;
    }

    // -----------------------------------------------------------------------
    // Bidirectional morphisms
    // -----------------------------------------------------------------------

    public static Map<Integer, Set<Integer>> phiMap(
            LatticeCarrier L, ZariskiTopology topology) {
        return new HashMap<>(topology.basicOpens);
    }

    public static Map<Integer, Integer> psiMap(
            LatticeCarrier L, List<PrimeIdeal> primes) {
        Map<Integer, Integer> out = new HashMap<>();
        for (int i = 0; i < primes.size(); i++) {
            PrimeIdeal p = primes.get(i);
            List<Integer> complement = new ArrayList<>();
            for (int a = 0; a < L.size(); a++) {
                if (!p.members.contains(a)) complement.add(a);
            }
            if (complement.isEmpty()) {
                out.put(i, L.bottomIdx);
                continue;
            }
            int acc = complement.get(0);
            for (int k = 1; k < complement.size(); k++) {
                acc = L.join[acc][complement.get(k)];
            }
            out.put(i, acc);
        }
        return out;
    }

    static Map<String, Boolean> checkMorphisms(
            LatticeCarrier L, ZariskiTopology topology) {
        List<PrimeIdeal> primes = topology.primes;
        Map<Integer, Set<Integer>> phi = phiMap(L, topology);
        Map<Integer, Integer> psi = psiMap(L, primes);

        boolean phiOp = true;
        outer:
        for (int a = 0; a < L.size(); a++) {
            for (int b = 0; b < L.size(); b++) {
                if (L.le[a][b] && !phi.get(b).containsAll(phi.get(a))) {
                    phiOp = false;
                    break outer;
                }
            }
        }

        boolean phiInj = true;
        Map<Set<Integer>, Integer> seen = new HashMap<>();
        for (int a = 0; a < L.size(); a++) {
            Set<Integer> img = phi.get(a);
            if (seen.containsKey(img) && seen.get(img) != a) {
                phiInj = false;
                break;
            }
            seen.put(img, a);
        }

        boolean psiWd = true;
        for (int i = 0; i < primes.size(); i++) {
            if (!psi.containsKey(i)) { psiWd = false; break; }
        }

        boolean duality = true;
        for (int i = 0; i < primes.size(); i++) {
            int a = psi.get(i);
            if (!phi.get(a).contains(i)) { duality = false; break; }
        }

        Map<String, Boolean> result = new HashMap<>();
        result.put("phi_order_preserving", phiOp);
        result.put("phi_injective", phiInj);
        result.put("psi_well_defined", psiWd);
        result.put("duality_holds", duality);
        return result;
    }
}
